export const mapClasses = [
    "variant-1",
    "variant-2",
    "variant-3",
    "variant-1",
    "variant-2",
    "variant-3",
    "variant-1",
    "variant-2",
    "variant-3",
    "variant-1",
]



export const backgrounds = [
  {
      img: "/images/backgrounds/blue/1.jpeg",
      title: "Background Blue 1",
      photographer: "Photographer Name",
      description: "Description for Blue 1.",
  },
  {
      img: "/images/backgrounds/blue/2.jpeg",
      title: "Background Blue 2",
      photographer: "Photographer Name",
      description: "Description for Blue 2.",
  },
  {
      img: "/images/backgrounds/blue/3.jpeg",
      title: "Background Blue 3",
      photographer: "Photographer Name",
      description: "Description for Blue 3.",
  },
  {
      img: "/images/backgrounds/dark/1.jpeg",
      title: "Background Dark 1",
      photographer: "Photographer Name",
      description: "Description for Dark 1.",
  },
  {
      img: "/images/backgrounds/dark/2.jpeg",
      title: "Background Dark 2",
      photographer: "Photographer Name",
      description: "Description for Dark 2.",
  },
  {
      img: "/images/backgrounds/dark/3.jpeg",
      title: "Background Dark 3",
      photographer: "Photographer Name",
      description: "Description for Dark 3.",
  },
  {
      img: "/images/backgrounds/green/1.jpeg",
      title: "Background Green 1",
      photographer: "Photographer Name",
      description: "Description for Green 1.",
  },
  {
      img: "/images/backgrounds/green/2.jpeg",
      title: "Background Green 2",
      photographer: "Photographer Name",
      description: "Description for Green 2.",
  },
  {
      img: "/images/backgrounds/green/3.jpeg",
      title: "Background Green 3",
      photographer: "Photographer Name",
      description: "Description for Green 3.",
  },
  {
      img: "/images/backgrounds/red/1.jpeg",
      title: "Background Red 1",
      photographer: "Photographer Name",
      description: "Description for Red 1.",
  },
  {
      img: "/images/backgrounds/red/2.jpeg",
      title: "Background Red 2",
      photographer: "Photographer Name",
      description: "Description for Red 2.",
  },
  {
      img: "/images/backgrounds/red/3.jpeg",
      title: "Background Red 3",
      photographer: "Photographer Name",
      description: "Description for Red 3.",
  },
  {
      img: "/images/backgrounds/white/1.jpeg",
      title: "Background White 1",
      photographer: "Photographer Name",
      description: "Description for White 1.",
  },
  {
      img: "/images/backgrounds/white/2.jpeg",
      title: "Background White 2",
      photographer: "Photographer Name",
      description: "Description for White 2.",
  },
  {
      img: "/images/backgrounds/white/3.jpeg",
      title: "Background White 3",
      photographer: "Photographer Name",
      description: "Description for White 3.",
  },
  {
      img: "/images/backgrounds/white/4.jpeg",
      title: "Background White 4",
      photographer: "Photographer Name",
      description: "Description for White 4.",
  },
  {
      img: "/images/backgrounds/white/5.jpeg",
      title: "Background White 5",
      photographer: "Photographer Name",
      description: "Description for White 5.",
  },
];

export const previews = [
  {
      img: "/images/foregrounds/blue/1.jpeg",
      title: "Foreground Blue 1",
      photographer: "Photographer Name",
      description: "Description for Blue 1.",
  },
  {
      img: "/images/foregrounds/blue/2.jpeg",
      title: "Foreground Blue 2",
      photographer: "Photographer Name",
      description: "Description for Blue 2.",
  },
  {
      img: "/images/foregrounds/blue/3.jpeg",
      title: "Foreground Blue 3",
      photographer: "Photographer Name",
      description: "Description for Blue 3.",
  },
  {
      img: "/images/foregrounds/blue/4.jpeg",
      title: "Foreground Blue 4",
      photographer: "Photographer Name",
      description: "Description for Blue 4.",
  },
  {
      img: "/images/foregrounds/dark/1.jpeg",
      title: "Foreground Dark 1",
      photographer: "Photographer Name",
      description: "Description for Dark 1.",
  },
  {
      img: "/images/foregrounds/dark/2.jpeg",
      title: "Foreground Dark 2",
      photographer: "Photographer Name",
      description: "Description for Dark 2.",
  },
  {
      img: "/images/foregrounds/dark/3.jpeg",
      title: "Foreground Dark 3",
      photographer: "Photographer Name",
      description: "Description for Dark 3.",
  },
  {
      img: "/images/foregrounds/dark/4.jpeg",
      title: "Foreground Dark 4",
      photographer: "Photographer Name",
      description: "Description for Dark 4.",
  },
  {
      img: "/images/foregrounds/green/1.jpeg",
      title: "Foreground Green 1",
      photographer: "Photographer Name",
      description: "Description for Green 1.",
  },
  {
      img: "/images/foregrounds/green/2.jpeg",
      title: "Foreground Green 2",
      photographer: "Photographer Name",
      description: "Description for Green 2.",
  },
  {
      img: "/images/foregrounds/green/3.jpeg",
      title: "Foreground Green 3",
      photographer: "Photographer Name",
      description: "Description for Green 3.",
  },
  {
      img: "/images/foregrounds/red/1.jpeg",
      title: "Foreground Red 1",
      photographer: "Photographer Name",
      description: "Description for Red 1.",
  },
  {
      img: "/images/foregrounds/red/2.jpeg",
      title: "Foreground Red 2",
      photographer: "Photographer Name",
      description: "Description for Red 2.",
  },
  {
      img: "/images/foregrounds/red/3.jpeg",
      title: "Foreground Red 3",
      photographer: "Photographer Name",
      description: "Description for Red 3.",
  },
  {
      img: "/images/foregrounds/white/1.jpeg",
      title: "Foreground White 1",
      photographer: "Photographer Name",
      description: "Description for White 1.",
  },
  {
      img: "/images/foregrounds/white/2.jpeg",
      title: "Foreground White 2",
      photographer: "Photographer Name",
      description: "Description for White 2.",
  },
  {
      img: "/images/foregrounds/white/3.jpeg",
      title: "Foreground White 3",
      photographer: "Photographer Name",
      description: "Description for White 3.",
  },
  {
      img: "/images/foregrounds/white/4.jpeg",
      title: "Foreground White 4",
      photographer: "Photographer Name",
      description: "Description for White 4.",
  },
];
